version: '2'

services:
  pg:
    image: postgres:11
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: boom
      POSTGRES_USER: root
      POSTGRES_DB: black_marlin
    volumes:
    - ./storage/pg:/var/lib/postgresql/data

  consul:
    image: consul
    ports:
    - "8500:8500"
