version: '2'

services:
  database:
    image: postgres:11
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: boom
      POSTGRES_DB: black_marlin_api

  consul:
    image: consul
    ports:
    - 8500:8500

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
    - 15672:15672
    - 5672:5672
